# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created: Fri Mar 16 11:39:18 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from tank.platform.qt import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(793, 471)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.columnsSplitter = QtGui.QSplitter(Dialog)
        self.columnsSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.columnsSplitter.setObjectName("columnsSplitter")
        self.dateWidget = QtGui.QWidget(self.columnsSplitter)
        self.dateWidget.setObjectName("dateWidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dateWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ingestDate = QtGui.QWidget(self.dateWidget)
        self.ingestDate.setObjectName("ingestDate")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.ingestDate)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.dateLabel = QtGui.QLabel(self.ingestDate)
        self.dateLabel.setObjectName("dateLabel")
        self.horizontalLayout_2.addWidget(self.dateLabel)
        self.dateLineEdit = QtGui.QLineEdit(self.ingestDate)
        self.dateLineEdit.setObjectName("dateLineEdit")
        self.horizontalLayout_2.addWidget(self.dateLineEdit)
        self.verticalLayout_3.addWidget(self.ingestDate)
        self.takeView = QtGui.QTableView(self.dateWidget)
        self.takeView.setObjectName("takeView")
        self.verticalLayout_3.addWidget(self.takeView)
        self.filesWidget = QtGui.QWidget(self.columnsSplitter)
        self.filesWidget.setObjectName("filesWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.filesWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scanDir = QtGui.QWidget(self.filesWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scanDir.sizePolicy().hasHeightForWidth())
        self.scanDir.setSizePolicy(sizePolicy)
        self.scanDir.setObjectName("scanDir")
        self.horizontalLayout = QtGui.QHBoxLayout(self.scanDir)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dirLabel = QtGui.QLabel(self.scanDir)
        self.dirLabel.setObjectName("dirLabel")
        self.horizontalLayout.addWidget(self.dirLabel)
        self.dirLineEdit = QtGui.QLineEdit(self.scanDir)
        self.dirLineEdit.setObjectName("dirLineEdit")
        self.horizontalLayout.addWidget(self.dirLineEdit)
        self.dirButton = QtGui.QPushButton(self.scanDir)
        self.dirButton.setObjectName("dirButton")
        self.horizontalLayout.addWidget(self.dirButton)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addWidget(self.scanDir)
        self.fileView = QtGui.QTableView(self.filesWidget)
        self.fileView.setObjectName("fileView")
        self.verticalLayout.addWidget(self.fileView)
        self.verticalLayout_2.addWidget(self.columnsSplitter)
        self.buttonTrayWidget = QtGui.QWidget(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonTrayWidget.sizePolicy().hasHeightForWidth())
        self.buttonTrayWidget.setSizePolicy(sizePolicy)
        self.buttonTrayWidget.setObjectName("buttonTrayWidget")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.buttonTrayWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ingestButton = QtGui.QPushButton(self.buttonTrayWidget)
        self.ingestButton.setObjectName("ingestButton")
        self.horizontalLayout_3.addWidget(self.ingestButton)
        self.verticalLayout_2.addWidget(self.buttonTrayWidget)
        self.verticalLayout_2.setStretch(0, 1)
        self.actionScanFiles = QtGui.QAction(Dialog)
        self.actionScanFiles.setObjectName("actionScanFiles")
        self.actionIngestFiles = QtGui.QAction(Dialog)
        self.actionIngestFiles.setObjectName("actionIngestFiles")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Ingest Shootday Files...", None, QtGui.QApplication.UnicodeUTF8))
        self.dateLabel.setText(QtGui.QApplication.translate("Dialog", "ShootDay", None, QtGui.QApplication.UnicodeUTF8))
        self.dirLabel.setText(QtGui.QApplication.translate("Dialog", "Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.dirButton.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.ingestButton.setText(QtGui.QApplication.translate("Dialog", "Ingest qtake files to versions on mocap takes...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionScanFiles.setText(QtGui.QApplication.translate("Dialog", "ScanFiles", None, QtGui.QApplication.UnicodeUTF8))
        self.actionScanFiles.setToolTip(QtGui.QApplication.translate("Dialog", "Scan Files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIngestFiles.setText(QtGui.QApplication.translate("Dialog", "Ingest Files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIngestFiles.setToolTip(QtGui.QApplication.translate("Dialog", "Make Versions for files linked to takes", None, QtGui.QApplication.UnicodeUTF8))

from . import resources_rc
